name: Build GCC-CrossCompiler Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t tss-crosscomp-dev-env .

    uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /usr/local/cross
